Init:
  unstash: []
  stashes:
    - name: "source"
      includes: "**/*"
      excludes: ".pipeline/**"

'Pull-Request Voting':
  unstash:
    - source
  stashes: []

Build:
  unstash:
    - source
  stashes:
    # configuration copied from pipelineStashFilesAfterBuild (default_pipeline_environment)
    - name: 'buildResult'
      includes: '**/target/*.war, **/target/*.jar, **/*.mtar, **/*.jar.original, dist/*'
      excludes: ''
    - name: 'checkmarx'
      includes: '**/*.js, **/*.scala, **/*.py, **/*.go, **/*.d, **/*.di, **/*.xml, **/*.html, **/*.ts'
      excludes: '**/*.mockserver.js, node_modules/**/*.js'
    - name: 'checkmarxOne'
      includes: '**/*.js, **/*.scala, **/*.py, **/*.go, **/*.d, **/*.di, **/*.xml, **/*.html, **/*.ts'
      excludes: '**/*.mockserver.js, node_modules/**/*.js'
    - name: 'classFiles'
      includes: '**/target/classes/**/*.class, **/target/test-classes/**/*.class'
      excludes: ''
    - name: 'sonar'
      includes: '**/jacoco*.exec, **/sonar-project.properties'
      excludes: ''

Integration:
  unstash:
    - source
    - buildResult
  stashes: []

Acceptance:
  unstash:
    - buildDescriptor
    - buildResult
    - deployDescriptor
  stashes: []

Compliance:
  unstash:
    - source
  stashes: []

Performance:
  unstash:
    - source
    - buildResult
  stashes: []

Release:
  unstash:
    - buildDescriptor
    - buildResult
    - deployDescriptor
  stashes: []
